apiVersion: v1
kind: Service
metadata:
  name: {{ include "weecuba-dotnet-service.fullname" . }}
  labels:
    {{- include "weecuba-dotnet-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.metrics.enabled }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.targetPort }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "weecuba-dotnet-service.selectorLabels" . | nindent 4 }}
